FROM ubuntu:24.04 as main

ENV TERM="xterm-256color"

RUN \
    apt-get update        && \
    apt-get install --yes    \
                    --no-install-recommends \
                    build-essential      \
                    binutils \
                    build-essential \
                    ca-certificates \
                    git-all \
                    gfortran \
                    libfabric-dev \
                    libstdc++-14-dev \
                    libxml2-dev \
                    libcurl4-openssl-dev \
                    m4 \
                    python3 \
                    python3-pip \
                    python3-venv \
                    python-is-python3 \
                    rsync \
                    software-properties-common \
            	    wget \
                    zlib1g-dev \
                    libssl-dev autoconf automake libtool \
                    python3-dev          \
                    wget              && \
    apt-get install -y python3-pip && \
    apt-get clean all && \
    ldconfig



COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD []
ENTRYPOINT ["/entrypoint.sh"]
