ARG ACCT="C-Worthy"
ARG FROM_TAG="latest"

ARG INSTALL_BASE_DIR="/opt"
ARG PROFILE_DIR="/etc/profile.d"
# NERSC Base Container
#  OS: OpenSuse

FROM opensuse/leap:15.6
WORKDIR /opt

# Build options
ARG TARGETPLATFORM
ARG TARGETARCH
ARG TARGETOS

RUN zypper --non-interactive install \
    curl                      \
    autoconf                  \
    automake                  \
    cmake                     \
    libtool                   \
    flex                      \
    python3                   \
    unzip                     \
    git                       \
    mlocate                   \
    git                       \
    tmux                      \
    fish                      \
    gzip                      \
    bzip2                     \
    libpmi0                   \
    slurm                     \
    vim                       \
    gcc-c++                   \
    gcc                       \
    gfortran \
    make                      \
    wget                   && \
    rm -rf /var/cache/zypp/*


# Install CUDA toolkit
ARG CUDA_VERSION=12.4.0
WORKDIR /tmp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    export RUN_NAME=cuda_${CUDA_VERSION}_550.54.14_linux.run; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    export RUN_NAME=cuda_${CUDA_VERSION}_550.54.14_linux_sbsa.run; \
    fi && \
    wget -q https://developer.download.nvidia.com/compute/cuda/${CUDA_VERSION}/local_installers/${RUN_NAME} -O cuda_${CUDA_VERSION}.run && \
    sh cuda_${CUDA_VERSION}.run --toolkit --silent && \
    rm -rf cuda_${CUDA_VERSION}.run

ENV CPATH=/usr/local/cuda/include:$CPATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda:$PATH
ENV PATH=/usr/local/cuda/bin:$PATH
ENV CUDA_ROOT=/usr/local/cuda
ENV CUDA_HOME=/usr/local/cuda
ENV CUDA_TOOLKIT_DIR=/usr/local/cuda

# Install nvptx-tools
WORKDIR /tmp
RUN git clone --depth=1 https://github.com/SourceryTools/nvptx-tools.git && \
    cd nvptx-tools                                                       && \
    ./configure --with-cuda-driver-include=/usr/local/cuda/include          \
    --with-cuda-driver-lib=/usr/local/cuda/lib64                            \
    --prefix=/opt/nvptx/install                                          && \
    make -j 4                                                            && \
    make install                                                         && \
    cd ..  && rm -rf nvptx-tools

# Install GCC
ARG NPROC=2
ARG GCC_VERSION=13.2.0
WORKDIR /tmp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    export ARCH=x86_64; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    export ARCH=aarch64; \
    fi && \
    git clone --depth=1 git://sourceware.org/git/newlib-cygwin.git nvptx-newlib && \
    git clone --depth=1 -b releases/gcc-$GCC_VERSION https://github.com/gcc-mirror/gcc.git gcc && \
    cd gcc                                                                                     && \
    contrib/download_prerequisites                                                             && \
    ln -s ../nvptx-newlib/newlib newlib                                                        && \
    cd ..                                                                                      && \
    mkdir build_nvptx_gcc                                                                      && \
    cd build_nvptx_gcc                                                                         && \
    ../gcc/configure CC=/usr/bin/gcc CXX=/usr/bin/g++                   \
    --host=${ARCH}-linux-gnu --target=nvptx-none                        \
    --with-build-time-tools=/opt/nvptx/install/nvptx-none/bin           \
    --enable-as-accelerator-for=${ARCH}-pc-linux-gnu                    \
    --disable-sjlj-exceptions --enable-newlib-io-long-long              \
    --enable-languages="c,c++,fortran,lto" --prefix=/opt/gcc/install && \
    make -j ${NPROC}                                                 && \
    make -j ${NPROC} install                                         && \
    cd ..                                                            && \
    mkdir build_host_gcc                                             && \
    cd build_host_gcc                                                && \
    ../gcc/configure CC=/usr/bin/gcc CXX=/usr/bin/g++                   \
    --enable-offload-targets=nvptx-none                                 \
    --with-cuda-driver-include=/usr/local/cuda/include                  \
    --with-cuda-driver-lib=/usr/local/cuda/lib64                        \
    --disable-bootstrap --disable-multilib                              \
    --enable-languages="c,c++,fortran,lto" --prefix=/opt/gcc/install && \
    make -j ${NPROC}                                                 && \
    make -j ${NPROC} install                                         && \
    cd .. && rm -rf /tmp/build_host_gcc \
    /tmp/build_nvptx_gcc \
    /tmp/gcc

ENV PATH=/opt/gcc/install/bin:$PATH
ENV PATH=/opt/gcc/install/include:$PATH
ENV LD_LIBRARY_PATH=/opt/gcc/install/lib:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/opt/gcc/install/lib64:$LD_LIBRARY_PATH


# Install libfabric
ARG LIBFABRIC_VERSION=1.20.0
WORKDIR /tmp
RUN wget -q https://github.com/ofiwg/libfabric/archive/v${LIBFABRIC_VERSION}.tar.gz && \
    tar xf v${LIBFABRIC_VERSION}.tar.gz                                             && \
    cd libfabric-${LIBFABRIC_VERSION}                                               && \
    ./autogen.sh                                                                    && \
    ./configure --prefix=/usr  --enable-only --enable-cxi --enable-tcp --enable-rxm    \
                 --enable-udp --enable-shm --enable-sm2 --enable-rxd                   \
                 --enable-hook_hmem --enable-hook_debug --enable-dmabuf_peer_mem    && \
    make -j 8                                                                       && \
    make install                                                                    && \
    ldconfig                                                                        && \
    cd ..                                                                           && \
    rm -rf v${LIBFABRIC_VERSION}.tar.gz libfabric-${LIBFABRIC_VERSION}

#                 --enable-rxd  --enable-udp --enable-shm --enable-sm2               && \

# Install OpenMPI  using libfabric 
ARG OPENMPI_VERSION=5.0.6
WORKDIR /tmp
RUN wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-$OPENMPI_VERSION.tar.gz && \
    tar xf openmpi-$OPENMPI_VERSION.tar.gz                                                   && \
    cd openmpi-$OPENMPI_VERSION                                                              && \
    ./configure --with-libfabric=/usr                                                           \
    --prefix=/usr                                                                               \
    --with-slurm                                                                                \
    --with-pmix                                                                              && \
    make -j 8                                                                                && \
    make install                                                                             && \
    ldconfig                                                                                 && \
    cd ..                                                                                    && \
    rm -rf openmpi-$OPENMPI_VERSION.tar.gz openmpi-$OPENMPI_VERSION

# Install AOCL
ARG AOCL_VERSION=5.0.0
WORKDIR /tmp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    wget -q https://download.amd.com/developer/eula/aocl/aocl-5-0/aocl-linux-gcc-${AOCL_VERSION}.tar.gz && \
    tar -xvzf aocl-linux-gcc-${AOCL_VERSION}.tar.gz                                                  && \
    cd aocl-linux-gcc-${AOCL_VERSION}                                                                && \
    ./install.sh ;\
    elif [ "$TARGETARCH" = "arm64" ]; then \
    echo "Not installing AOCL on ARM"; \
    fi


# Puts you back in the root users home directory
WORKDIR /root


ARG SRC_DIR="/install"

ARG HDF5_PROFILE="/etc/profile.d/hdf5.sh"
ARG HDF5_INSTALL_DIR="hdf5-1.14.6-install"
ARG HDF5_TAR="hdf5_1.14.6.tar.gz"
ARG HDF5_URL="https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5_1.14.6.tar.gz"

ENV HDF5_HOME=$INSTALL_BASE_DIR/$HDF5_INSTALL_DIR
ENV HDF5_SRC=$SRC_DIR/hdf5-hdf5_1.14.6

WORKDIR $SRC_DIR


ARG NETCDF_V="4.9.3"
ARG NETCDF_TAR="v$NETCDF_V.tar.gz"
ARG NETCDF_URL="https://github.com/Unidata/netcdf-c/archive/refs/tags/$NETCDF_TAR"

ARG NETCDF_FV="4.6.2"
ARG NETCDF_FORTRAN_TAR="v$NETCDF_FV.tar.gz"
ARG NETCDF_FORTRAN_URL="https://github.com/Unidata/netcdf-fortran/archive/refs/tags/$NETCDF_FORTRAN_TAR"

ARG NETCDF_SRC="$SRC_DIR/netcdf-c-$NETCDF_V"
ARG NETCDF_HOME="$INSTALL_BASE_DIR/netcdf-$NETCDF_V-install"
ARG NETCDF_FORTRAN_SRC="$SRC_DIR/netcdf-fortran-$NETCDF_FV"
ARG NETCDF_FORTRAN_HOME="$INSTALL_BASE_DIR/netcdf-fortran-$NETCDF_FV-install"


WORKDIR "$SRC_DIR"


ENV NETCDF_DIR=/opt/cray/pe/netcdf/4.9.0.9/gnu/12.3

ENV MPIHOME=/opt/cray/pe/mpich/8.1.30/ofi/gnu/12.3
ENV NETCDFHOME=/opt/cray/pe/netcdf/4.9.0.9/gnu/12.3/
ENV HDF5_HOME=/opt/cray/pe/hdf5/1.14.3.1/gnu/12.3

ENV PATH=$MPIHOME/bin:$NETCDFHOME/bin:$HDF5_HOME/bin:$ROMS_PATH:$PATH
ENV LD_LIBRARY_PATH=$MPIHOME/lib:$NETCDF_FORTRAN_HOME/lib:$NETCDF_HOME/lib:$HDF5_HOME/lib:/opt/cray/pe/lib64/:$LD_LIBRARY_PATH
ENV CPATH=$MPIHOME/include:$NETCDF_FORTRAN_HOME/include:$NETCDF_HOME/include:HDF5_HOME/include:$CPATH
ENV LIBRARY_PATH=$$MPIHOME/lib:NETCDF_FORTRAN_HOME/lib:$NETCDF_HOME/lib:$HDF5_HOME/lib:$LIBRARY_PATH
ENV LD_RUN_PATH="$MPIHOME/lib:$NETCDF_FORTRAN_HOME/lib:$NETCDF_HOME/lib:$HDF5_HOME/lib:/opt/cray/pe/lib64/:$LD_RUN_PATH"
RUN /sbin/ldconfig


ARG MARBL_BASENAME=marbl0.45.0
ARG TGZ_NAME="$MARBL_BASENAME.tar.gz"
ARG REPO_MARBL="https://github.com/marbl-ecosys/MARBL/archive/refs/tags/$TGZ_NAME"

ENV MARBL_ROOT=$INSTALL_BASE_DIR/$MARBL_BASENAME
ARG MARBL_PROFILE=/etc/profile.d/marbl.sh


RUN wget -q "$REPO_MARBL" && \
    tar xvf "$TGZ_NAME" && \
    mv MARBL-$MARBL_BASENAME $MARBL_ROOT && \
    rm "$TGZ_NAME" && \
    cd "$MARBL_ROOT/src" && \
    which mpifort && which mpif90 && env && sleep 2 && \
    make USEMPI=TRUE FC=mpif90 && \
    echo "export MARBL_ROOT=$MARBL_ROOT" >> $MARBL_PROFILE


ENV CSTAR_INTERACTIVE="0"
ENV GIT_DISCOVERY_ACROSS_FILESYSTEM="1"


ARG ROMS_BASENAME=mpi-masking
ENV ROMS_ROOT=$INSTALL_BASE_DIR/ucla-roms 
ENV ROMS_PATH=$ROMS_ROOT/Tools-Roms
ARG REPO_ROMS="https://github.com/ScottEilerman/ucla-roms/archive/refs/heads/$ROMS_BASENAME.tar.gz"
ENV ROMS_PROFILE="/etc/profile.d/ucla-roms.sh"

RUN echo "export ROMS_ROOT=$ROMS_ROOT" >> $ROMS_PROFILE && \
    echo "export ROMS_PATH=$ROMS_PATH" >> $ROMS_PROFILE && \
    echo 'export PATH=$PATH:$ROMS_PATH' >> $ROMS_PROFILE

RUN . /etc/profile && \
    wget -q "$REPO_ROMS" && \
    tar xvf $ROMS_BASENAME.tar.gz && \
    mv ucla-roms-$ROMS_BASENAME "$ROMS_ROOT" && \
    rm $ROMS_BASENAME.tar.gz

WORKDIR /opt
RUN mkdir -p /opt/work_internal/compile_time_code

RUN \
    cd "$ROMS_ROOT/Work" && \
    make tools-roms COMPILER=gnu

ENV PATH=$PATH:$ROMS_PATH

COPY * /opt/work_internal/compile_time_code

RUN cd /opt/work_internal/compile_time_code && make compile_clean && make COMPILER=gnu

# add these to end of roms compile if you need debug outputs:
#BUILD_MODE=debug KEEP_PPSRC=true
