ARG ACCT="C-Worthy"
ARG FROM_TAG="latest"
ARG IMG_NCDF="$ACCT/cstar-netcdf:$FROM_TAG"

FROM $IMG_NCDF

ARG REDO=1
ARG SRC_DIR="/install"
ARG INSTALL_BASE_DIR=/opt
ENV ROMS_ROOT=$INSTALL_BASE_DIR/ucla-roms 
ENV ROMS_PATH=$ROMS_ROOT/Tools-Roms
ARG ROMS_BASENAME=mpi-masking
ARG REPO_ROMS="https://github.com/ScottEilerman/ucla-roms/archive/refs/heads/$ROMS_BASENAME.tar.gz"
ENV ROMS_PROFILE="/etc/profile.d/ucla-roms.sh"

WORKDIR "$SRC_DIR"

RUN echo "export ROMS_ROOT=$ROMS_ROOT" >> $ROMS_PROFILE && \
    echo "export ROMS_PATH=$ROMS_PATH" >> $ROMS_PROFILE && \
    echo 'export PATH=$PATH:$ROMS_PATH' >> $ROMS_PROFILE

RUN . /etc/profile && \
    wget -q "$REPO_ROMS" && \
    tar xvf $ROMS_BASENAME.tar.gz && \
    mv ucla-roms-$ROMS_BASENAME "$ROMS_ROOT" && \
    rm $ROMS_BASENAME.tar.gz


#RUN \
#    cd "$ROMS_ROOT/Work" && \
#    make tools-roms COMPILER=gnu
ENV PATH=$PATH:$ROMS_PATH

WORKDIR $INSTALL_BASE_DIR

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD []
ENTRYPOINT ["/entrypoint.sh"]

